//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagementPortal.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobManagementDBEntities : DbContext
    {
        public JobManagementDBEntities()
            : base("name=JobManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_contactus> tbl_contactus { get; set; }
        public virtual DbSet<tbl_disciplines> tbl_disciplines { get; set; }
        public virtual DbSet<tbl_employers> tbl_employers { get; set; }
        public virtual DbSet<tbl_job_application> tbl_job_application { get; set; }
        public virtual DbSet<tbl_job_disciplines> tbl_job_disciplines { get; set; }
        public virtual DbSet<tbl_student_disciplines> tbl_student_disciplines { get; set; }
        public virtual DbSet<tbl_students> tbl_students { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<tbl_vacancies> tbl_vacancies { get; set; }
    }
}
