//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagementPortal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_disciplines
    {
        public int Id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> discipline_id { get; set; }
    
        public virtual tbl_disciplines tbl_disciplines { get; set; }
        public virtual tbl_students tbl_students { get; set; }
    }
}
