//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagementPortal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employers
    {
        public int Id { get; set; }
        public string company_name { get; set; }
        public string company_location { get; set; }
        public string company_description { get; set; }
        public int user_id { get; set; }
    
        public virtual tbl_users tbl_users { get; set; }
    }
}
