//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagementPortal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vacancies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_vacancies()
        {
            this.tbl_job_application = new HashSet<tbl_job_application>();
            this.tbl_job_disciplines = new HashSet<tbl_job_disciplines>();
        }
    
        public int Id { get; set; }
        public string post { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public string status { get; set; }
        public int user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_job_application> tbl_job_application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_job_disciplines> tbl_job_disciplines { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
